# Generated by Django 2.1.2 on 2018-11-05 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20181102_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antonym',
            old_name='base_word',
            new_name='form_word',
        ),
        migrations.RenameField(
            model_name='synonym',
            old_name='base_word',
            new_name='form_word',
        ),
    ]
