# Generated by Django 2.1.3 on 2018-12-04 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_auto_20181129_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordlistowner',
            old_name='user_id',
            new_name='user',
        ),
    ]
