# Generated by Django 2.1.2 on 2018-12-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_auto_20181204_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordlist',
            name='word',
        ),
        migrations.RemoveField(
            model_name='wordlist',
            name='word_list',
        ),
        migrations.RemoveField(
            model_name='wordlistowner',
            name='user',
        ),
        migrations.DeleteModel(
            name='WordList',
        ),
        migrations.DeleteModel(
            name='WordListOwner',
        ),
    ]
