# Generated by Django 2.1.3 on 2018-12-09 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_auto_20181205_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antonym',
            name='antonym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.VariantWord'),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='synonym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.VariantWord'),
        ),
    ]
