# Generated by Django 2.1.2 on 2018-12-10 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_auto_20181209_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antonym',
            name='form_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.BaseWord'),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='form_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.BaseWord'),
        ),
    ]
