# Generated by Django 2.1.2 on 2018-12-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_auto_20181210_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
