# Generated by Django 2.1.2 on 2018-12-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0013_wordlist_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
