# Generated by Django 2.1.3 on 2018-12-14 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0014_wordlist_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynonymsToLookUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_word', models.CharField(max_length=50)),
                ('is_synonym', models.BooleanField()),
                ('base_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.BaseWord')),
            ],
        ),
    ]
