# Generated by Django 2.1.2 on 2018-12-27 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0016_auto_20181227_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_guesses', models.PositiveIntegerField()),
                ('correct_guesses', models.PositiveIntegerField()),
                ('base_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.BaseWord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
