# Generated by Django 2.1.2 on 2018-12-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0016_load_static_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseword',
            name='correct_guesses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baseword',
            name='total_guesses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
