# Generated by Django 2.1.2 on 2018-12-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0018_load_static_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccuracy',
            name='correct_guesses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useraccuracy',
            name='total_guesses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
